[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "finos-cdm"
version = "6.4.0"
description = "FINOS Common Domain Model – generated Python classes"
requires-python = ">=3.9"